const DocumentHashMap: any = {
    // 容器布局
    "box": "Box 弹性布局",
    "divider": "Divider 分割线",
    "flex": "flex 弹性容器",
    "grid": "Grid 栅格",
    "page": "Page 页面",
    "panel": "Panel 面板",
    "wrap": "wrap 容器",
    // 数据处理
    "auto-action": "AutoAction 自动执行",
    "iterator": "Iterator 迭代器",
    "map": "Map 映射组件",
    "tpl": "Tpl 模板语法",
    "virtual": "Virtual 虚拟组件",
    "watch": "Watch 监控",
    // 基础组件
    "button": "Button 按钮",
    "button-dropdown": "ButtonDropDown 下拉按钮",
    "button-group": "ButtonGroup 按钮组",
    "icon": "Icon 图标",
    "move-button": "MoveButton 拖拽移动",
    "auto-complete": "AutoComplete 输入建议",
    "upload": "Upload 文件上传",
    "checkbox": "Checkbox 复选框",
    "city-select": "CitySelect 城市选择器",
    "color-picker": "ColorPicker 颜色选择器",
    "combo": "Combo 复合组件",
    "combo-table": "ComboTable 复合组件",
    "combo-tabs": "ComboTabs 复合组件",
    "date-picker": "DatePicker 日期选择",
    "editor": "Editor 富文本编辑器",
    "form": "Form 表单",
    "form-item": "FormItem 表单项组件",
    "input": "Input 输入框",
    "cascader": "Cascader 级联选择器",
    "mark": "Mark 评分",
    "multi-cascader": "MultiCascader 级联多选选择器",
    "radio": "Radio 单选框",
    "range-picker": "RangePicker 日期段选择器",
    "select": "Select 选择器",
    "slider": "Slider 滑块",
    "switch": "Switch 开关",
    "tag-input": "TagInput 标签输入组件",
    "tag-select": "TagSelect 标签选择组件",
    "textarea": "Textarea 文本域",
    "time-picker": "TimePicker 时间选择器",
    "tree": "Tree 树",
    "input-number": "InputNumber 计数器",
    // 数据展示
    "accordion": "Accordion 手风琴",
    "video": "Video 视频",
    "crud": "Crud 增删改查",
    "date": "Date 日期展示",
    "ellipsis": "Ellipsis 文本自动省略",
    "image": "Image 图片预览",
    "lock": "Lock 高密组件",
    "countdown": "CountDown 倒计时",
    // "quick-edit": "QuickEdit 快速编辑",
    // "selection-transfer": "SelectionTransfer 行选择穿梭框",
    "table": "Table 表格",
    "tag": "Tag 标签",
    "timeline": "Timeline 时间轴",
    "transpose-table": "TransposeTable 转置表格",
    "progress": "Progress 进度条",
    // 导航组件
    "breadcrumb": "Breadcrumb 面包屑",
    "pagination": "Pagination 分页",
    "steps": "Steps 步骤条",
    "tabs": "Tabs 选项卡",
    // 提示通知
    "alert": "Alert 信息提示",
    "dialog": "Dialog 对话框",
    "tooltip": "Tooltip 鼠标提示",
    // 其他
    "iframe": "Iframe",
    "schema": "Schema 动态渲染",
    // 虚拟组件到关联文档的映射
    "column": "Table 表格",
    "v-tab-item": "Tabs 选项卡",
    "v-grid-col": "Grid 栅格",
    "v-step": "Steps 步骤条",
    "v-box-col": "Box 弹性布局",
    "v-combo-tab": "ComboTabs 复合组件",
    "v-accordion-panel": "Accordion 手风琴"
};

export default DocumentHashMap;